customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "G"
    command: "aicommits"
    description: "commit with aicommits"
    context: "files"
    loadingText: "generating ai commit message"
    subprocess: true
