customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
gui:
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - "#E5E5E5"
    selectedRangeBgColor:
      - "#E5E5E5"
  border: "rounded"
# os:
#   edit: "nvim"
#   editCommandTemplate: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
# open: '{{editor}} --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
# open: 'nvim --server /tmp/nvim-server.pipe --remote-tab "$(pwd)/{{filename}}"'
